In [1]:
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn import datasets
from numpy import array
from pandas import DataFrame
from pandas import concat
from keras.models import model_from_json
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder


Using TensorFlow backend.


In [2]:
def rmse(objetivo, estimaciones):
    return np.sqrt(metrics.mean_squared_error(objetivo, estimaciones)
                  )

In [3]:
def  ajustested_r2(objetivo, estimaciones,n,k):
    r2=metrics.r2_score(objetico,estimaciones)
    return 1-(1-r2)*(n-1)/(n-k-1)

In [4]:
def evaluar_modelo(objetivo,estimaciones,n,k):
    return {
        "rmse":rmse(objetivo,estimaciones),
        "mae": metrics.mean_absolute_error(objetivo,estimaciones),
        "ajustested_r2": ajustested_r2(objetivo,estimaciones,n,k)
    }

In [14]:
def ejecutar_prueba_modelo(valores):
    
    #Cargo el modelo antes generado.
    json_file = open('../Modelamiento/model.json', 'r')
    loaded_model_json = json_file.read()
    json_file.close()
    loaded_model = model_from_json(loaded_model_json)
    # Cargo el nuevo modelo
    loaded_model.load_weights("../Modelamiento/LTSM_Cali_3meses.h5")


    valores = valores.values
    valores = valores.astype('float32')
    scaler = MinMaxScaler(feature_range=(0, 1))
    scaled = scaler.fit_transform(valores)

    #Remodelar la entrada para que sea 3D [muestras, pasos de tiempo, características]
    train_X = scaled.reshape((scaled.shape[0], 1, scaled.shape[1]))
    train_X.shape

    yhat = loaded_model.predict(train_X, verbose=0)
    scalerSalida = MinMaxScaler(feature_range=(0, 1))
    scaledSalida = scalerSalida.fit_transform(yhat)
    yhat= scalerSalida.inverse_transform(yhat)

    
    print(yhat)
   

In [12]:
#Prueba manual con los datos 
#PM10
#DirVien
#H2S
#Humedad
#Lluvia
#NO2
#O3
#CO
#RSolar
#SO2
#Tasa_crecimiento_general
#Temp
#VelVien
x_input = np.array([20,148.6000061,0,72.69999695,1.269999981,0,17.64,2851.524414,
                    302.7999878,12.91359997,0.097400002,24.89999962,1.299999952])
print(x_input.shape)

df = pd.DataFrame({ 'Motos_vehiculos_particulares':    [5989541,5390586.9, 4581998.865, 348066],
                    'Lluvia': [0.939613,0.382813,0.263171911239624,0.572834014892578],
                    'Poblacion': [2244668,2244668,2244668, 2244668]
                   })



(13,)


In [15]:
salida=ejecutar_prueba_modelo(df)

[[0.28751555]
 [0.26103845]
 [0.25362277]
 [0.25546294]]


In [20]:
dataOriginal = pd.read_excel('../PreparacionDatos/FloraTotal_3mes_3V_mas_4.xlsx' , sheet_name='FloraTotal' ,header=0)
dataOriginal=dataOriginal.drop(['Trimestre'], axis=1)

In [45]:
dataOriginal

Motos_vehiculos_particulares    Lluvia   Poblacion
0                     348066.000  0.939613  2244668.00
1                     348066.000  0.382813  2244668.00
2                     348066.000  0.263172  2244668.00
3                     348066.000  0.572834  2244668.00
4                     391327.000  0.190382  2269653.00
5                     391327.000  0.413592  2269653.00
6                     391327.000  0.408934  2269653.00
7                     391327.000  0.595508  2269653.00
8                     438769.000  0.060729  2294653.00
9                     438769.000  0.426957  2294653.00
10                    438769.000  0.107707  2294653.00
11                    438769.000  0.419806  2294653.00
12                    484119.000  0.185106  2319684.00
13                    484119.000  0.276111  2319684.00
14                    484119.000  0.134173  2319684.00
15                    484119.000  0.472869  2319684.00
16                    526339.000  0.215647  2344734.00
17                    526339.000  0.234257  2344734.00
18                    526339.000  0.281555  2344734.00
19                    526339.000  0.372491  2344734.00
20                    567353.000  0.208546  2369821.00
21                    567353.000  0.193502  2369821.00
22                    567353.000  0.110047  2369821.00
23                    567353.000  0.124192  2369821.00
24                    601794.000  0.265361  2394925.00
25                    601794.000  0.253803  2394925.00
26                    601794.000  0.088913  2394925.00
27                    601794.000  0.280813  2394925.00
28                    630478.000  0.015700  2420114.00
29                    630478.000  0.181820  2420114.00
30                    630478.000  0.148639  2420114.00
31                    630478.000  0.220213  2420114.00
32                   5989541.000  0.232976  2589521.98
33                   5390586.900  0.282742  2589521.98
34                   4581998.865  0.187975  2589521.98
35                   3665599.092  0.364326  2589521.98

In [21]:
salida=ejecutar_prueba_modelo(dataOriginal)

[[0.27059582]
 [0.24523598]
 [0.23982777]
 [0.25386995]
 [0.2400872 ]
 [0.25020882]
 [0.2499968 ]
 [0.2585075 ]
 [0.23780487]
 [0.2544364 ]
 [0.2399233 ]
 [0.25410965]
 [0.24701735]
 [0.25116652]
 [0.24470167]
 [0.26017472]
 [0.25201532]
 [0.2528668 ]
 [0.25503308]
 [0.2592055 ]
 [0.2553138 ]
 [0.2546236 ]
 [0.25080097]
 [0.25144804]
 [0.2615448 ]
 [0.2610121 ]
 [0.25342965]
 [0.2622572 ]
 [0.25366223]
 [0.2613088 ]
 [0.2597784 ]
 [0.26308098]
 [0.31063557]
 [0.31052843]
 [0.30250823]
 [0.30701396]]


In [46]:
salida=ejecutar_prueba_modelo(dataOriginal[35:36])


[[0.30739456]]


In [47]:
salida=ejecutar_prueba_modelo(dataOriginal[34:36])

[[0.25162548]
 [0.25719354]]


In [48]:
salida=ejecutar_prueba_modelo(dataOriginal[33:36])

[[0.23708466]
 [0.22124475]
 [0.23537347]]


In [50]:
salida=ejecutar_prueba_modelo(dataOriginal[32:36])

[[0.21947867]
 [0.2225272 ]
 [0.20831837]
 [0.22352733]]


In [49]:
salida=ejecutar_prueba_modelo(dataOriginal[31:36])

[[0.24712975]
 [0.3476104 ]
 [0.36084333]
 [0.3240156 ]
 [0.37701416]]


In [51]:
salida=ejecutar_prueba_modelo(dataOriginal[30:36])

[[0.21338682]
 [0.23317583]
 [0.34127718]
 [0.35214558]
 [0.31881702]
 [0.36420864]]
